### ISSUE TITLE
A bug while getting train information from 12306

### ISSUE THREAD

**Issue by dqwfgzs** [ZHZHH-Arezrh5100/rail-line-animation-toolkit#1]
Hi, while I pull down train information from 12306 by running query_schedule_12306.py, there is a error in line 12, the information is here:
"Exception has occurred: ModuleNotFoundError
No module named 'numpy'
  File "/home/lenovo/rail-line-animation-toolkit/schedule_data/query_schedule_12306.py", line 12, in <module>
    import numpy as np
How to resolve it

**Comment by ZHZHH-Arezrh5100** [comment]
> Hi, while I pull down train information from 12306 by running query_schedule_12306.py, there is a error in line 12, the information is here:
> "Exception has occurred: ModuleNotFoundError
> No module named 'numpy'
> File "/home/lenovo/rail-line-animation-toolkit/schedule_data/query_schedule_12306.py", line 12, in 
> import numpy as np
> How to resolve it

I can run this script in Python 3.6.4 with numpy.
Did you install numpy in your python?
(You can run `pip list` or `pip3 list` in console to see if numpy is installed.)

**Comment by ZHZHH-Arezrh5100** [comment]
You can try 'import numpy' in Python. If the same error occured, there might be something wrong with the installation of numpy, and maybe this thread can help you: https://stackoverflow.com/questions/7818811/import-error-no-module-named-numpy

If you use pycharm and anaconda, you can refer to this (Chinese): https://blog.csdn.net/john_bian/article/details/7929122
