### ISSUE TITLE
The 12306 query address has been expired

### ISSUE THREAD

**Issue by dqwfgzs** [ZHZHH-Arezrh5100/rail-line-animation-toolkit#2]
The 12306 query address has been expired. 
When I try to pull down from 12306, the command is:
"C:\WINDOWS\system32>python "C:\Users\dqwfg\Desktop\rail-line-animation-toolkit\schedule_data\query_schedule_12306.py"

TRAIN SCHEDULE DATA for Train Animation Generator
- Query train schedule data from 12306.cn

Please input the date of the schedule (YYYY-mm-dd): 2019-02-20
Please input the default icon id: 1

- Command Codes:
-- [1] Add trains by train names.
-- [2] Add trains by two station code.
-- [8] Preset command 1 (Shanghai -> Hangzhou)
-- [9] Preset command 2 (Hangzhou -> Shanghai)
-- [0] EXIT
Please input a command code: 2
Add trains by two station code.
From (Station code): SBT
Exclude other station in the same city? (y/[n]): n
To (Station code): DLT
Exclude other station in the same city? (y/[n]): n
Train class filter: G,D
Default track id (1/2): 1
Default direction (U/D): U
Querying trains info...
Failed to decode train information from 12306!
Data is empty! No data to save.

**Comment by ZHZHH-Arezrh5100** [comment]
Thank you!
The up-to-date 12306 query address in "query_schedule_12306.py" have been updated.
So the script should work as normal now.
